### ISSUE TITLE
Document/improve support for FastMail IMAP alt-namespace mode

### ISSUE THREAD

**Issue by wjt** [lamby/tickle-me-email#6]
In [Two-step verification and other new security features](https://blog.fastmail.com/2016/07/25/two-step-verification-and-other-new-security-features/), FastMail recommend using `imap.fastmail.com` in future, and describes changes to how folders are exposed. The effect on `tickle-me-email list` is as follows:
- With `mail.messagingengine.com`: `INBOX.DELAYED.01`
- With `imap.fastmail.com`: `(\HasNoChildren) "/" DELAYED/01` – [here's](https://gist.github.com/wjt/7643706e26d242a577b014928ff384f8) how the full `DELAYED` tree looks now

What should one use in one's cronjob as a parameter to `tickle-me-email rotate`? The full line, including the `(\HasNoChildren)` cruft?

**Comment by lamby** [comment]
> What should one use in one's cronjob as a parameter to tickle-me-email rotate

Does either of them even work?

(I wouldn't like to pass that cruft to `rotate` anyway just from the aesthetics...)

**Comment by wjt** [comment]
Lazy of me not to just try them. This works: `tickle-me-email move DELAYED/Evening INBOX`. So it looks like the following is no longer enough to get a human-readable folder name list:

``` python
        for x in self.imap.list()[1]:
            print x.split(' "." ')[-1]
```

because `"."` may not be the folder separator. Perhaps there is a way to get the separator out of the imap library? (cf. [this blog post](https://blog.fastmail.com/2016/07/13/whats-in-a-name-mailbox-names-via-imap/))

**Comment by lamby** [comment]
Thanks! Can you test this and I'll do a release ... ?

**Comment by wjt** [comment]
It works!
