### ISSUE TITLE
Handle (modified) UTF-7-encoded folder names(?)

### ISSUE THREAD

**Issue by wjt** [lamby/tickle-me-email#7]
If I create a folder called “DELAYED/☃”, `tickle-me-email list` displays it as `DELAYED/&JgM-`. This seems to be because of the convention of using [modified UTF-7](https://tools.ietf.org/html/rfc2060#section-5.1.3) for folder names.

Using the UTF-7-encoded form for commands like `move`, `rotate` works fine, so maybe this is just “resolved: don't do that”. But if one is concerned about the æsthetics of the `list` output…?

**Comment by lamby** [comment]
Good catch. Released!
